from tkinter import *

def click(event):
 global scvalue
 text=event.widget.cget(&quot;text&quot;)
 print(text)
 if text == &quot;=&quot;:
   if scvalue.get().isdigit():
     value=int(scvalue.get())
   else:

     value=eval(scvalue.get())
     scvalue.set(value)
     screen.update()
   elif text==&quot;C&quot;:
      scvalue.set(&quot;&quot;)
      screen.update()
else:
   scvalue.set(scvalue.get()+text)
   screen.update()
root=Tk()
root.geometry(&quot;500x800&quot;)
p1 = PhotoImage(file = &#39;facebook.png&#39;)
root.iconphoto(False,p1)
# root.iconbitmap(&quot;facebook.png&quot;)
scvalue=StringVar()
scvalue.set(&quot;&quot;)
screen=Entry(root,textvar=scvalue,font=&quot;lucida 30
bold&quot;)
screen.pack(fill=X,padx=5,pady=10)
f=Frame(root,bg=&quot;grey&quot;)
b=Button(f,text=&quot;9&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
b=Button(f,text=&quot;8&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
b=Button(f,text=&quot;7&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
f.pack()

f=Frame(root,bg=&quot;grey&quot;)
b=Button(f,text=&quot;6&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
b=Button(f,text=&quot;5&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)

b=Button(f,text=&quot;4&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
f.pack()
f=Frame(root,bg=&quot;grey&quot;)
b=Button(f,text=&quot;3&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
b=Button(f,text=&quot;2&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
b=Button(f,text=&quot;1&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
f.pack()

f=Frame(root,bg=&quot;grey&quot;)
b=Button(f,text=&quot;+&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
b=Button(f,text=&quot;-&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
b=Button(f,text=&quot;*&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
f.pack()

f=Frame(root,bg=&quot;grey&quot;)
b=Button(f,text=&quot;/&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
b=Button(f,text=&quot;%&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
b=Button(f,text=&quot;=&quot;,font=&quot;lucida 30 bold&quot;)

b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
f.pack()

f=Frame(root,bg=&quot;grey&quot;)
b=Button(f,text=&quot;C&quot;,font=&quot;lucida 30 bold&quot;)
b.pack(side=LEFT,padx=20,pady=10)
b.bind(&quot;&lt;Button-1&gt;&quot;,click)
f.pack()
root.mainloop()